apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-demoapp
  namespace: prod
spec:
  rules:
  - host: nodejs-prod.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http
            port:
              name: http